version: 0.7.2.{build}
image: Visual Studio 2019


environment:
  matrix:
    - PlatformToolset: v142

platform:
    - x64
    - Win32

configuration:
    - Release
    - Debug


install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="Win32" set platform_input=Win32

    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild IndentByFold.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        if ($env:PLATFORM_INPUT -eq "x64") {
            #Push-AppveyorArtifact "$env:PLATFORM_INPUT\$env:CONFIGURATION\IndentByFold.dll" -FileName IndentByFold.dll
        }

        if ($env:PLATFORM_INPUT -eq "Win32" ) {
            #Push-AppveyorArtifact "$env:PLATFORM_INPUT\$env:CONFIGURATION\IndentByFold.dll" -FileName IndentByFold.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v142") {
            if($env:PLATFORM_INPUT -eq "x64"){
                $ZipFileName = "IndentByFold_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
                7z a $ZipFileName $env:PLATFORM_INPUT\$env:CONFIGURATION\IndentByFold.dll
            }
            if($env:PLATFORM_INPUT -eq "Win32"){
                $ZipFileName = "IndentByFold_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
                7z a $ZipFileName $env:PLATFORM_INPUT\$env:CONFIGURATION\IndentByFold.dll
            }
        }

artifacts:
  - path: IndentByFold_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v142
        configuration: Release
